---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r, echo=TRUE, message=FALSE, results="hide"}
#Update settings and load necessary packages
Sys.setlocale("LC_ALL", "English")
library(dplyr)
```

## Loading and preprocessing the data
```{r, echo=TRUE, cache=TRUE}
#Read the data into a dataframe
df <- read.csv("activity.csv", stringsAsFactors=FALSE)

#Convert factor to date
df$date <- as.Date(df$date)

#Show summary
str(df)
```

## What is mean total number of steps taken per day?
```{r, echo=TRUE, cache=TRUE}
#Calculate number of steps per day
steps.per.day <- df %>%
    filter(!is.na(steps)) %>%
    group_by(date) %>%
    summarise(steps=sum(steps))
head(steps.per.day)

#Plot a histogram of steps per day
hist(steps.per.day$steps, breaks=20)

#Report the mean ot the number of steps per day
mean(steps.per.day$steps, na.rm=TRUE)

#Report the median ot the number of steps per day
median(steps.per.day$steps, na.rm=TRUE)
```

## What is the average daily activity pattern?
```{r, echo=TRUE, cache=TRUE}
#Calculate average number of steps per interval
avg.steps.per.interval <- df %>%
    filter(!is.na(steps)) %>%
    group_by(interval) %>%
    summarise(steps=mean(steps))
head(avg.steps.per.interval)

#Make a time series plot
plot(avg.steps.per.interval$interval, avg.steps.per.interval$steps, type="l",
     main="Average number of steps per interval")

#Report interval with maximum namber of steps
avg.steps.per.interval[which.max(avg.steps.per.interval$steps), ]
```

## Imputing missing values
```{r, echo=TRUE, cache=TRUE}
#Report the total number of missing values in the dataset
sum(is.na(df$steps))

#Create a new dataframe with missing values filled in using the mean
#for the corresponding 5-minute interval
df.filled <- df
missing.values <- is.na(df.filled$steps)
avg.values <- tapply(df.filled$steps, df.filled$interval, mean, na.rm=TRUE,
                     simplify=TRUE)
df.filled$steps[missing.values] <-
    avg.values[as.character(df.filled$interval[missing.values])]

#Calculate number of steps per day
steps.per.day.filled <- df.filled %>%
    filter(!is.na(steps)) %>%
    group_by(date) %>%
    summarise(steps=sum(steps))
head(steps.per.day.filled)

#Plot a histogram of steps per day
hist(steps.per.day.filled$steps, breaks=20)

#Report the mean ot the number of steps per day
mean(steps.per.day.filled$steps, na.rm=TRUE)

#Report the median ot the number of steps per day
median(steps.per.day.filled$steps, na.rm=TRUE)
```
The median value of steps per day increased slightly due to filling in the missing values.

## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE, cache=TRUE}
#Create a new column distinguishing between weekdays and weekends
df.filled <- mutate(df.filled, daytype = ifelse(weekdays(df.filled$date) == "Saturday" | weekdays(df.filled$date) == "Sunday", "weekend", "weekday"))
df.filled$daytype <- as.factor(df.filled$daytype)
head(df.filled)

#Create and reshape separate dataframes for weekdays and weekends
df.weekdays <- df.filled[df.filled$daytype == "weekday", ]
df.weekends <- df.filled[df.filled$daytype == "weekend", ]
avg.steps.per.interval.weekdays <- df.weekdays %>%
    group_by(interval) %>%
    summarise(steps=mean(steps))
avg.steps.per.interval.weekends <- df.weekends %>%
    group_by(interval) %>%
    summarise(steps=mean(steps))

#Create a panel plot
par(mfrow = c(2, 1))
plot(avg.steps.per.interval.weekdays$interval,
     avg.steps.per.interval.weekdays$steps,
     type="l",
     main="Weekdays",
     xlab="interval",
     ylab="average number of steps")
plot(avg.steps.per.interval.weekends$interval,
     avg.steps.per.interval.weekends$steps,
     type="l",
     main="Weekends",
     xlab="interval",
     ylab="average number of steps")
```